#!/data/data/com.termux/files/usr/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso mixtureViscosityModels
wclean libso relativeVelocityModels
wclean

#------------------------------------------------------------------------------
